name: Merge requests tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
          scope: '@gatewatcher'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
